language: objective-c
osx_image: xcode10.2

branches:
    only:
    - master

script:
  - set -o pipefail && xcodebuild test -project Macaw.xcodeproj -scheme 'Macaw iOS' -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,OS=12.2,name=iPhone X' | xcpretty;
  - set -o pipefail && xcodebuild build -project Macaw.xcodeproj -scheme 'MacawOSX' ONLY_ACTIVE_ARCH=NO | xcpretty;

notifications:
    slack: exyte:kdo9FNtTOFMuMqAyyvZPDAD7
