#!/bin/bash
set -euo pipefail

# If swiftlint is building for the first time we want it to use
# the default SDK for the platform not the one set by the build script
unset SDKROOT

: "${CARTHAGE:=NO}"

if [ "$CARTHAGE" != "YES" ]; then
  ./Tools/mint/mint run swiftlint \
    --quiet \
    -- \
    Package.swift \
    Sources \
    AfterpayTests
fi
