#!/bin/bash
set -euo pipefail

# If swiftlint is building for the first time we want it to use
# the default SDK for the platform not the one set by the build script
unset SDKROOT

# The Mintfile is specified in the directory above
cd ..

./Tools/mint/mint run swiftlint \
  --quiet \
  --path Example \
  --config ../.swiftlint.yml
