name: Build and Test

env:
  afterpay-scheme: Afterpay
  DEVELOPER_DIR: /Applications/Xcode_11.5.app/Contents/Developer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-and-test:
    name: Build and Test
    runs-on: macos-latest

    env:
      destination: platform=iOS Simulator,name=iPhone 11,OS=13.5
      example-scheme: Example
      workspace: Afterpay.xcworkspace

    steps:
    - uses: actions/checkout@v2

    - name: Cache Mint Packages
      uses: actions/cache@v2
      with:
        path: /usr/local/lib/mint
        key: ${{ runner.os }}-mint-${{ hashFiles('Mintfile') }}
        restore-keys: |
          ${{ runner.os }}-mint-

    - name: Install Dependencies
      run: |
        Tools/mint/mint bootstrap
        gem install cocoapods

    - name: SwiftLint
      run: Tools/mint/mint run swiftlint --reporter github-actions-logging

    - name: Validate Pod
      run: pod lib lint

    - name: Build SDK Project
      run: |
        xcodebuild build-for-testing \
          -workspace ${{ env.workspace }} \
          -scheme ${{ env.afterpay-scheme }} \
          -destination '${{ env.destination }}'
  
    - name: Test SDK Project
      run: |
        xcodebuild test-without-building \
          -workspace ${{ env.workspace }} \
          -scheme ${{ env.afterpay-scheme }} \
          -destination '${{ env.destination }}'

    - name: Build Example Project
      run: |
        xcodebuild \
          -workspace ${{ env.workspace }} \
          -scheme ${{ env.example-scheme }} \
          -destination '${{ env.destination }}'

  validate-cocoapods:
    name: Validate Pod
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Dependencies
      run: gem install cocoapods

    - name: Validate Pod
      run: |
        export LIB_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)
        pod lib lint

  validate-swift-package:
    name: Validate Swift Package
    runs-on: macos-latest

    env:
      destination: platform=macOS,variant=Mac Catalyst
      workspace: .swiftpm/xcode/package.xcworkspace

    steps:
    - uses: actions/checkout@v2

    - name: Validate Swift Package
      run: |
        xcodebuild \
          -workspace ${{ env.workspace }} \
          -scheme ${{ env.afterpay-scheme }} \
          -destination '${{ env.destination }}'
